language: python
python:
  - "3.9"

stages:
  - test1

jobs:
  include:
    - stage: test1
      name: test1 nazwa
      script:
        - sudo apt install python3-pip
        - sudo pip install BeatifulSoup4
        - python -m pytest test/
