language: python
python:
  - "3.9"

# command to install dependencies
install:
  - pip install -r requirements.txt

stages:
  - test1

jobs:
  include:
    - stage: test1
      name: test1 nazwa
      script:
        - python -m pytest test/
