language: python
python:
  - "3.9"

stages:
  - test1

jobs:
  include:
    - stage: test1
      name: test1 nazwa
      script:
        - python -m pytest test/
        
before_install:
- sudo pip install BeatifulSoup4
